/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pageform;

import Pageform.editUser;
import Pageform.tambahUser;
import Pageform.koneksi;
import Pageform.Profile;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import

/**
 *
 * @author acer
 */
public class menuAdmin extends javax.swing.JFrame {
    Profile p;
    private Profile P;
    private static DefaultTableModel m = new DefaultTableModel();
    private static DefaultTableModel mod_p = new DefaultTableModel();

    public Connection con;
    public Statement stm;
    public ResultSet rs;
    

    /**
     * Creates new form menuAdmin
     */
    public menuAdmin() {
        initComponents();
        settingTable();
        viewData("");
        viewDataProduct("");
    }

    menuAdmin(Profile P) {
         initComponents();
         settingTable();
         viewData("");
         viewDataProduct("");
         

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Pn_user = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txttambah = new javax.swing.JButton();
        txthapus = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        txtedit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbluser = new javax.swing.JTable();
        Pn_produk = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        txtSearch = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataProduk = new javax.swing.JTable();
        Pn_transaksi = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(102, 153, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(641, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(533, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_START);

        Pn_user.setBackground(new java.awt.Color(255, 255, 255));
        Pn_user.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(641, 70));

        txttambah.setBackground(new java.awt.Color(51, 255, 0));
        txttambah.setText("TAMBAH");
        txttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttambahActionPerformed(evt);
            }
        });

        txthapus.setBackground(new java.awt.Color(255, 0, 0));
        txthapus.setText("HAPUS");
        txthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthapusActionPerformed(evt);
            }
        });

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        jButton4.setText("Search");

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setText("Refresh");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        txtedit.setBackground(new java.awt.Color(255, 255, 0));
        txtedit.setText("EDIT");
        txtedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txttambah, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtedit)
                .addGap(12, 12, 12)
                .addComponent(txthapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addGap(25, 25, 25)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttambah)
                    .addComponent(txthapus)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton9)
                    .addComponent(txtedit))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Pn_user.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tbluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id user", "Username", "password", "Role"
            }
        ));
        jScrollPane1.setViewportView(tbluser);

        Pn_user.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Data user", Pn_user);

        Pn_produk.setBackground(new java.awt.Color(255, 255, 255));
        Pn_produk.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(641, 70));

        jButton5.setBackground(new java.awt.Color(51, 255, 0));
        jButton5.setText("TAMBAH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 0));
        jButton6.setText("EDIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setText("HAPUS");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        txtSearch.setText("Search");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setText("Refresh");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(12, 12, 12)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addGap(26, 26, 26)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtSearch)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch)
                    .addComponent(jButton10))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Pn_produk.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        tblDataProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_produk", "nama_Produk", "rasa", "Diproduksi_oleh ", "stok", "waktu_EXP", "Harga"
            }
        ));
        jScrollPane2.setViewportView(tblDataProduk);

        Pn_produk.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Data produk", Pn_produk);

        Pn_transaksi.setBackground(new java.awt.Color(255, 255, 255));
        Pn_transaksi.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(641, 70));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Pn_transaksi.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jTabbedPane2.addTab("Data transaksi", Pn_transaksi);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selamat Datang Admin");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jLabel4.setText("Username:");

        jLabel5.setText("Password");

        jLabel6.setText("Role");

        jTextField1.setText("Azmi");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPasswordField1.setText("123");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", " ", "Admin", "User", " ", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Profile", jPanel4);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttambahActionPerformed
        // TODO add your handling code here:
    tambahUser t = new tambahUser();
    t.setVisible(true);

    }//GEN-LAST:event_txttambahActionPerformed

    private void txthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthapusActionPerformed
        // TODO add your handling code here:
        int n = tbluser.getSelectedRow();
        if (n != -1) {
        int id = Integer.parseInt(tbluser.getValueAt(n, 0).toString());
        String username = tbluser.getValueAt(n, 1).toString();

        int opsi = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus data " + username + "?", 
                "Hapus Data", 
                JOptionPane.YES_NO_OPTION);

        if (opsi == JOptionPane.YES_OPTION) {
            String Q = "DELETE FROM user WHERE id_user = ?";

            try {
                Connection K = koneksi.connectionDb();
                PreparedStatement ps = K.prepareStatement(Q);
                ps.setInt(1, id);
                ps.executeUpdate();
                viewData(""); 
                JOptionPane.showMessageDialog(this, "Data " + username + " telah terhapus");
//                Logging.saveLog("berhasil menghapus user " + username);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
        } else {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus terlebih dahulu.");
        }
    }//GEN-LAST:event_txthapusActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Tambah_produk t = new Tambah_produk();
        t.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
           int n = tblDataProduk.getSelectedRow();
        if (n != -1) {
        int id = Integer.parseInt(tblDataProduk.getValueAt(n, 0).toString());
        String nama_produk = tblDataProduk.getValueAt(n, 1).toString();

        int opsi = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin menghapus data " + nama_produk + "?", 
                "Hapus Data", 
                JOptionPane.YES_NO_OPTION);

        if (opsi == JOptionPane.YES_OPTION) {
            String Q = "DELETE FROM user WHERE id_user = ?";

            try {
                Connection K = koneksi.connectionDb();
                PreparedStatement ps = K.prepareStatement(Q);
                ps.setInt(1, id);
                ps.executeUpdate();
                viewData(""); 
                JOptionPane.showMessageDialog(this, "Data " + nama_produk + " telah terhapus");
                Logging.saveLog("berhasil menghapus user " + nama_produk);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
        } else {
        JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus terlebih dahulu.");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         int n = tblDataProduk.getSelectedRow();
        if(n != -1){
//            int id_produk = Integer.parseInt(tblDataProduk.getValueAt(n, 0).toString());
            String nama_Produk = tblDataProduk.getValueAt(n, 1).toString();
            String Rasa = tblDataProduk.getValueAt(n, 2).toString();
            String diproduksiOleh = tblDataProduk.getValueAt(n, 2).toString();
            int stok = Integer.parseInt(tblDataProduk.getValueAt(n, 0).toString());
            int waktuEXP = Integer.parseInt(tblDataProduk.getValueAt(n, 0).toString());
            int harga = Integer.parseInt(tblDataProduk.getValueAt(n, 0).toString());
            String Role = tblDataProduk.getValueAt(n, 3).toString();

    
            edit_produk EU = new edit_produk();
//            EU.setId_produk(id_produk);           
            EU.setnama_Produk(nama_Produk);     
            EU.setRasa(Rasa);   
            EU.setRasa(diproduksiOleh);   
            EU.setStok(stok);   
            EU.setEXP(waktuEXP);   
            EU.setHarga(harga);   
            EU.setRole(Role);   
                      
            EU.setVisible(true);       

        } else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
        }
         
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteditActionPerformed
        int n = tbluser.getSelectedRow();
        if(n != -1){
            int id_user = Integer.parseInt(tbluser.getValueAt(n, 0).toString());
            String Username = tbluser.getValueAt(n, 1).toString();
            String Password = tbluser.getValueAt(n, 2).toString();
            String Role = tbluser.getValueAt(n, 3).toString();

    
            editUser EU = new editUser();
            EU.setId_user(id_user);           
            EU.setUsername(Username);     
            EU.setPassword(Password);   
            EU.setLevel(Role);           
            EU.setVisible(true);       

        } else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
        }
    }//GEN-LAST:event_txteditActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
//        try {
//            DefaultTableModel model = (DefaultTableModel)tblDataProduk.getModel();
//            for (int i = model.getRowCount() - 1; i >= 0; i--){
//                model.removeRow(i);
//                
//            }
//            
//            Connection k =koneksi.connectionDb();
//            String keyword = txtSearch.getText();
//            
//            String query = " SELECT * FROM produk WHERE nama_Produk LIKE?";
//            PreparedStatement ps = k.prepareStatement(query);
//            ps.setString(1, "%" + keyword + "%");
//            
//            ResultSet rs = ps.executeQuery();
//            
//            while (rs.next()){
//                int id_produk = rs.getInt("id_produk");
//                String nama_Produk = rs.getString("nama_Produk");
//                String rasa = rs.getString("rasa");
//                String diproduksi_oleh = rs.getString("diproduksi_oleh");
//                int stok = rs.getInt("stok");
//                int waktu_EXP = rs.getInt("waktu_EXP");
//                double harga = rs.getDouble("harga");
//                
//                object[]rowData = {
//                    rs.getInt("id_produk"),
//                    rs.getString("nama_Produk"),
//                    rs.getString("rasa"),
//                    rs.getString("diproduksi_oleh"),
//                    rs.getInt("stok"),
//                    rs.getInt("waktu_EXP"),
//                    rs.getDouble("harga")
//                };
//                model.addRow(rowData);
//            }
//            ps.close();
//            rs.close();
//            k.close();
//            
//            
//        } catch (SQLException e){
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(null, "terjadi kesalahan saat mencari produk:" + e.getMessage());
//        }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
        
//        String key = txtsearch.getText();
//        String where = "WHERE "
////                + "FULLNAME LIKE '%" + key + "%' OR "
//                + "USERNAME LIKE '%" + key + "%' OR "
//                + "PASSWORD LIKE '%" + key + "%' OR "
//                + "ROLE LIKE '%" + key + "%'";
    }//GEN-LAST:event_txtsearchActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pn_produk;
    private javax.swing.JPanel Pn_transaksi;
    private javax.swing.JPanel Pn_user;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tblDataProduk;
    private javax.swing.JTable tbluser;
    private javax.swing.JButton txtSearch;
    private javax.swing.JButton txtedit;
    private javax.swing.JButton txthapus;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JButton txttambah;
    // End of variables declaration//GEN-END:variables
public static void viewData(String where) {
        try {
            // Menghapus semua baris sebelumnya di tabel
            for (int i = m.getRowCount() - 1; i >= 0; i--) {
                m.removeRow(i);
            }

            Connection  K = koneksi.connectionDb();
            Statement S = K.createStatement();

            // Menyusun query SQL dengan klausa WHERE jika ada
            String Q = "SELECT * FROM user ";
            if (!where.isEmpty()) {
                Q += " " + where; // Menambahkan klausa WHERE dari parameter
            }

            ResultSet R = S.executeQuery(Q);
            int no = 1;
            while (R.next()) {
                int id = R.getInt("id_user");
                String username = R.getString("Username");
                String password = R.getString("password");
                String level = R.getString("Role");

                Object[] D = {id, username, password, level};
                m.addRow(D);
                no++;
            }
//            Logging.saveLog("Berhasil Menampilkan data User");
        } catch (SQLException e) {
            e.printStackTrace();
        }
}

public static void viewDataProduct(String where) {
    try {
        // Hapus baris yang ada di model
        for (int i = mod_p.getRowCount() - 1; i >= 0; i--) {
            mod_p.removeRow(i);
        }

        Connection K = koneksi.connectionDb();
        Statement S = K.createStatement();
        String Q = "SELECT * FROM produk " + where;
        ResultSet R = S.executeQuery(Q);
        int no = 1;
        while (R.next()) {
            int id_produk = R.getInt("id_produk");
            String nama_Produk = R.getString("nama_Produk");
            String rasa = R.getString("rasa");
            String diproduksi_oleh = R.getString("diproduksi_oleh");
            int stok = R.getInt("stok");
            String waktu_EXP = R.getString("waktu_EXP");
            String harga = R.getString("harga");

            // Sesuaikan urutan data dengan urutan kolom di tabel UI
            Object[] D = {
                id_produk, nama_Produk, rasa, diproduksi_oleh, stok, waktu_EXP, harga
            };
            mod_p.addRow(D);

            no++;
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}


private void settingTable() {
        m = (DefaultTableModel) tbluser.getModel();
        tbluser.getColumnModel().getColumn(0).setMinWidth(50);
        tbluser.getColumnModel().getColumn(0).setMaxWidth(70);

        tbluser.getColumnModel().getColumn(0).setMinWidth(50);
        tbluser.getColumnModel().getColumn(0).setMaxWidth(70);
//        tbluser.getColumnModel().getColumn(1).setMinWidth(0);
//        tbluser.getColumnModel().getColumn(1).setMaxWidth(0);

        tbluser.getColumnModel().getColumn(2).setMinWidth(350);
        tbluser.getColumnModel().getColumn(2).setMaxWidth(500);
    
        
        // Ambil model tabel dari tblDataProduk
        mod_p = (DefaultTableModel) tblDataProduk.getModel();

        // Set lebar kolom sesuai dengan kebutuhan
        tblDataProduk.getColumnModel().getColumn(0).setMinWidth(50);  // ID produk
        tblDataProduk.getColumnModel().getColumn(0).setMaxWidth(70);

        tblDataProduk.getColumnModel().getColumn(1).setMinWidth(150); // Nama Produk
        tblDataProduk.getColumnModel().getColumn(1).setMaxWidth(300);

        tblDataProduk.getColumnModel().getColumn(2).setMinWidth(100); // Rasa
        tblDataProduk.getColumnModel().getColumn(2).setMaxWidth(150);

        tblDataProduk.getColumnModel().getColumn(3).setMinWidth(150); // Diproduksi Oleh
        tblDataProduk.getColumnModel().getColumn(3).setMaxWidth(200);

        tblDataProduk.getColumnModel().getColumn(4).setMinWidth(70);  // Stok
        tblDataProduk.getColumnModel().getColumn(4).setMaxWidth(100);

        tblDataProduk.getColumnModel().getColumn(5).setMinWidth(100); // Waktu EXP
        tblDataProduk.getColumnModel().getColumn(5).setMaxWidth(150);

        tblDataProduk.getColumnModel().getColumn(6).setMinWidth(100); // Harga
        tblDataProduk.getColumnModel().getColumn(6).setMaxWidth(150);

    
    }

    private static class Logging {

        private static void saveLog(String string) {
            
        }

        public Logging() {
        }
    }


}
